trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      # Grant permission to run script
      chmod +x ./CI/setup.sh
      # Run the setup.sh script
      ./CI/setup.sh
    displayName: 'Preparing environment'
  - script: |
      # Deploy
      chmod +x ./CI/deploy.sh
      ./CI/deploy.sh
