trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      # Grant permission to run script
      chmod +x ./CI/setup.sh
      # Run the setup.sh script
      ./CI/setup.sh
    displayName: 'Preparing environment'
  - script: |
      # Deploy
      chmod +x ./CI/deploy.sh
      ./CI/deploy.sh $AZ_TENANT $AZ_USER $AZ_PWD $WEB_APP_NAME $RSC_GROUP
    displayName: 'Deploy'
    env:
      AZ_TENANT: $(AZ_TENANT)
      AZ_USER: $(AZ_USER)
      AZ_PWD: $(AZ_PWD)
      WEB_APP_NAME: $(WEB_APP_NAME)
      RSC_GROUP: $(RSC_GROUP)
