#Ref: https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/python-webapp?view=azure-devops
#budget-planner-conn-name
trigger:
  branches:
    include:
      - '*'

jobs:
- job: Development
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/development') #Targeted branch
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    VENV_CACHE_FOLDER:  $(Pipeline.Workspace)/venv
  steps:
  - task: Cache@2
    inputs:
      key: '"venv" | "$(Agent.OS)"'
      restoreKeys: |
        "venv" | "$(Agent.OS)"
      path: $(VENV_CACHE_FOLDER)
      cacheHitVar: VENV_CACHE_RESTORE
    displayName: Restore Cache
  - script: |
      chmod +x ./CI/setup.sh
      ./CI/setup.sh $(VENV_CACHE_FOLDER)
    displayName: Install requirements
    condition: eq(variables.VENV_CACHE_RESTORE, 'false')
  - script: |
      echo "Activating venv"
      source $(VENV_CACHE_FOLDER)/bin/activate
      echo "Running tests..."
      pytest ./tests
    displayName: Run Tests
  - bash: |
      export WEB_APP_NAME=budget-planner-development
      zip -r $WEB_APP_NAME.zip . -x '.??*'
      # Deploy
      chmod +x ./CI/deploy.sh
      ./CI/deploy.sh $AZ_TENANT $AZ_USER $AZ_PWD $WEB_APP_NAME $RSC_GROUP
    displayName: 'Deploy App to Azure Web App'
    env:
      AZ_TENANT: $(AZ_TENANT)
      AZ_USER: $(AZ_USER)
      AZ_PWD: $(AZ_PWD)
      RSC_GROUP: $(RSC_GROUP)

- job: Main
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main') #Targeted branch
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    VENV_CACHE_FOLDER:  $(Pipeline.Workspace)/venv
  steps:
  - script: |
      chmod +x ./CI/setup.sh
      ./CI/setup.sh $(VENV_CACHE_FOLDER)
    displayName: Install requirements
    condition: eq(variables.VENV_CACHE_RESTORE, 'false')
  - task: Cache@2
    inputs:
      key: '"appenv" | "$(Agent.OS)"'
      restoreKeys: |
        "appenv" | "$(Agent.OS)"
      path: $(VENV_CACHE_FOLDER)
      cacheHitVar: VENV_CACHE_RESTORE
    displayName: Cache AppEnv
  - script: |
      source $(VENV_CACHE_FOLDER)/bin/activate
      pytest ./tests
    displayName: Run Tests
  - bash: |
      export WEB_APP_NAME=bugeting-app
      zip -r $WEB_APP_NAME.zip . -x '.??*'
      # Deploy
      chmod +x ./CI/deploy.sh
      ./CI/deploy.sh $AZ_TENANT $AZ_USER $AZ_PWD $WEB_APP_NAME $RSC_GROUP
    displayName: 'Deploy App to Azure Web App'
    env:
      AZ_TENANT: $(AZ_TENANT)
      AZ_USER: $(AZ_USER)
      AZ_PWD: $(AZ_PWD)
      RSC_GROUP: $(RSC_GROUP)
