#Ref: https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/python-webapp?view=azure-devops
#budget-planner-conn-name
trigger:
  branches:
    include:
      - '*'

jobs:
- job: prepareEnv
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    VENV_CACHE_FOLDER:  $(Pipeline.Workspace)/appenv
  steps:
  - script: |
      chmod +x ./CI/setup.sh
      ./CI/setup.sh $(VENV_CACHE_FOLDER)
      pwd
    displayName: Install requirements
  - task: Cache@2
    inputs:
      key: '"appenv" | "$(Agent.OS)"'
      restoreKeys: |
        "appenv" | "$(Agent.OS)"
      path: $(VENV_CACHE_FOLDER)
    displayName: Cache AppEnv
