#Ref: https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/python-webapp?view=azure-devops
#budget-planner-conn-name
trigger:
  branches:
    include:
      - '*'

jobs:
- jobs: prepareEnv
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
        displayName: 'Python Version: $(pythonVersion)'
    - script: |
        chmod +x ./CI/setup.sh
        ./CI/setup.sh
      workingDirectory: $(projectRoot)
      displayName: "Install python dependencies"
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/Application$(Build.BuildId).zip'
        replaceExistingArchive: true
    - publish: $(Build.ArtifactStagingDirectory)/Application$(Build.BuildId).zip
      displayName: "Upload Package"
      artifact: drop
